### ISSUE TITLE
DeleteNode() very slow when lots of (hidden) nodes

### ISSUE THREAD

**Issue by overload73** [JAM-Software/Virtual-TreeView#1053]
Hi,

I have a tree populated with more or less 300000 nodes of which 250000 are hidden because of filtering.
All nodes have no parent except for the hidden root node. (AddChild with parent set to nil)

When deleting the nodes, the 'DetermineHiddenChildrenFlag' is being called which is going through all siblings of the hidden root node until it comes across a non hidden sibbling. This means that for every node deleting, there's an iteration of a big amount of nodes..

I understand that this is needed to determine if the 'expand' button for the root node has to be shown, but in this case the root/parent node is hidden.. Why does the 'DetermineHiddenChildrenFlag' has to be executed in such case? 

Thanks!

**Comment by joachimmarder** [comment]
> When deleting the nodes, the 'DetermineHiddenChildrenFlag' is being called 

Do you refer to the call in `TBaseVirtualTree.DeleteNode()`?

>  in this case the root/parent node is hidden.. Why does the 'DetermineHiddenChildrenFlag' has to be executed in such case?

I have no answer to this question, but I guess the code was that way when I adopted the project and this optimization was simply forgotten.

A sample project or a pull request would appreciated.

**Comment by overload73** [comment]
> Do you refer to the call in `TBaseVirtualTree.DeleteNode()`?
> 
Indeed.. 

Here's a sample project. Its based on the Minimal example included with VT.

Steps :
1/ Fill tree with 250000 nodes
2/ Hide first 200000 nodes
3/ Delete 50000 visible nodes

Takes around 93 seconds to delete the 50000 visible nodes.

Hope this helps
[Sample.zip](https://github.com/JAM-Software/Virtual-TreeView/files/6894693/Sample.zip)

**Comment by joachimmarder** [comment]
I can't comment much on the existing code that handles hidden / filtered nodes, as it was this way when I adopted the project and I personally never used the filtering feature.

I think it is generally correct that the `vsAllChildrenHidden` is re-evaluated if a child node is deleted, it could have been the last visible node.

You can speed up the code in your sample project (thanks for that) by using `VST.DeleteChildren(VST.RootNode);` instead of the for-loop. Then `DetermineHiddenChildrenFlag()` is not called.

What we could maybe do: in case `BeginUpdate()` was called, do not call `DetermineHiddenChildrenFlag()` but make sure `DetermineHiddenChildrenFlagAllNodes()` is called in `EndUpdate()`.

**Comment by joachimmarder** [comment]
I just noticed that it is done that way in several other places, so this seems to be the right way.

**Comment by joachimmarder** [comment]
@overload73: Please test the fix in your project.

**Comment by overload73** [comment]
thanks its working perfectly now!!
