### ISSUE TITLE
ChangeDelay not applied to IncrementalSearch

### ISSUE THREAD

**Issue by jdorlon-Quest** [JAM-Software/Virtual-TreeView#1069]
Hello,

  This broke sometime between versions 7.0 and 7.6.

  If I set ChangeDelay on TVirtualStringTree, and use the up/down arrow keys to navigate between nodes, it works as expected.   The OnChange event fires after the delay, so that if I hit up/down arrow key again before the timer expires, the OnChange event is only fired for the last node.

  It used to work the same way if I was navigating by IncrementalSearch.  If I typed quickly, the OnChange event would fire only after I stopped typing.   But now, if my incremental search keystrokes cause node multiple node changes, I am getting an OnChange event firing for each node.

  Is this an intentional change or is it a bug?

Thanks.

**Comment by joachimmarder** [comment]
> Is this an intentional change or is it a bug?

I don't think this was intentional, but it would be good to find the commit that was responsible for the change.

Anyway, I looked at the code and found at the end of `TBaseVirtualTree.HandleIncrementalSearch()` that the node is selected through `Selected[Run] := True`. Using `AddToSelection(Run, False)` instead should solve the problem, the last boolean parameter allows to control if the `OnChnage` even is fired synchronized or delayed. @jdorlon-Quest: Can you please test this?

**Comment by jdorlon-Quest** [comment]
@joachimmarder Yes, that fixes it.  Thank you.
