### ISSUE TITLE
Incompatible error when calling  VTAccessibilityFactory.GetAccessibilityFactory.CreateIAccessible(Self);

### ISSUE THREAD

**Issue by maddsen** [JAM-Software/Virtual-TreeView#1251]
Self=TVTBaseAncestorVcl 

but  ATree is expected. 

TVTAccessibilityFactory.CreateIAccessible(ATree: TBaseVirtualTree): IAccessible;

So system hangs.

**Comment by maddsen** [comment]
unit VirtualTrees.BaseAncestorVCL;
unit VirtualTrees.AccessibilityFactory;

**Comment by joachimmarder** [comment]
Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project as ZIP to your report that allows to replicate the problem. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug. If you already have a solution, please supply a patch file.

**Comment by maddsen** [comment]
Regarding Version Delphi 12 and VSV 8.03.
I see  many changes that happens from the time I first loaded and the latest version of VirtualStringView 8.03.
so maybe its  not possible to advice without all details .
How is it possible to findVirtual_Treeview version number in one or other units like VirtualTrees.pas? Or is it only headers in Git that show the version numbers?

**Comment by joachimmarder** [comment]
> How is it possible to findVirtual_Treeview version number in one or other units like VirtualTrees.pas?

It is not included there. It depends on which [release you download](https://github.com/JAM-Software/Virtual-TreeView/releases).

I added the unit `VirtualTrees.AccessibilityFactory` to the demo project `Advanced` and here to the unit `GeneralAbilitiesDemo` and the project compiles, no compiler errors.

**Comment by joachimmarder** [comment]
No further infromation on the problem was supplied in the past months, so I am closing this issue.
