### ISSUE TITLE
double-click clears selected checkboxes

### ISSUE THREAD

**Issue by vlad69** [JAM-Software/Virtual-TreeView#1255]
When checkboxes are enabled and used, double-clicking a node to expand it clears checkboxes in the entire tree. Please make this a configurable setting, or allow double-click to work without clearing checkboxes on all nodes

**Comment by joachimmarder** [comment]
Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project as ZIP to your report that allows to replicate the problem. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug. If you already have a solution, please supply a patch file.

**Comment by joachimmarder** [comment]
No further information was supplied on this issue, so I am closing it now.
