### ISSUE TITLE
Let toAutoTristateTracking to ignore invisible nodes

### ISSUE THREAD

**Issue by alanccw** [JAM-Software/Virtual-TreeView#1258]
Hi,

In my treeview, there is a root node, and it contains several child nodes, some nodes are visible, some are not.

I enable toAutoTristateTracking option. However, since I can only select the visible nodes, when all visible nodes are selected, the root node is still in mixed state, not in checked state.

Is there a way to ignore the invisible nodes so that as long as all visible nodes are selected, then the root node will become checked?

I attached my sample project.
[TestTreeView.zip](https://github.com/user-attachments/files/15929302/TestTreeView.zip)

**Comment by joachimmarder** [comment]
> Is there a way to ignore the invisible nodes

No, the nodes are just invisble but are still there. And the invisible nodes have a well defined check state. This check state does not change just because it gets hidden and it influences the check state of its parent node.

What you can do is setting `CheckTpe` to `ctNone` when you set them to be invisible.

**Comment by alanccw** [comment]
@joachimmarder 

That works perfectly. Thank you very much.
