### ISSUE TITLE
AutoScale wrongly assumes that node height only depends on font size

### ISSUE THREAD

**Issue by UweRaabe** [JAM-Software/Virtual-TreeView#1261]
After updating VirtualTreeView to the latest version I encountered a problem with nodes being smaller as designed.
![image](https://github.com/user-attachments/assets/703827cc-e4a7-4a29-8abf-b9684e280f6c)
To get enough space for the icons (24px) in the nodes, I set the `DefaultNodeHeight` to 26 during design time. At runtime the form is dpi-scaled to 150%, which is perfectly handling `DefaultNodeHeight` inside `ChangeScale`.

The problem here is that `AutoScale` changes `DefaultNodeHeight` to a value matching the font height, but the designed `DefaultNodeHeight` was deliberately chosen not to match the font height. My current workaround is to disable `toAutoChangeScale` and I guess that is the intended approach.

On the other side is there a decent `Height` value available from the `Images` property, which IMHO should give `AutoScale` a lower bound for the node height even if the font is smaller. Of course that complicates the scaling process a bit.

**Comment by joachimmarder** [comment]
> My current workaround is to disable toAutoChangeScale and I guess that is the intended approach.

Yes, the flag TVTAutoOption.toAutoChangeScale no longer controls if dpi-scaling takes places, this now happens automatically like in all other VCL controls. If this flag is set, the default node height and the header height are automatically scaled according to the used font. So far, the height was only increased to a minimum width so that the text is not cut off. But the height was never scaled down if the control was moved to a monitor with a smaller scaling. This now happens. See issue [#1206](https://github.com/JAM-Software/Virtual-TreeView/issues/1206). 

> On the other side is there a decent Height value available from the Images property, which IMHO should give AutoScale a lower bound for the node height even if the font is smaller.

I agree. I think this was not yet reported because you rarely have an image size that is significantly larger than the font size + `TextMargin`.

**Comment by joachimmarder** [comment]
Please let me know if the recent commit solves your problem.

**Comment by joachimmarder** [comment]
No response from reporter, considering this fixed.
