### ISSUE TITLE
DefaultNodeHeight ignores set value and recalculates to default

### ISSUE THREAD

**Issue by mitzix** [JAM-Software/Virtual-TreeView#1263]
I have TVirtualDrawTree and I want to set DefaultNodeHeight to 100. In older versions this setting was preserved. Now DefaultNodeHeight is recalculated to default value regardless I set it in design or run time. I tried to override this issue with setting toVariableNodeHeight and set NodeHeight in OnMeasureItem but it is very slow (for 100k items it takes ages).

**Comment by joachimmarder** [comment]
Since V8, the flag `TVTAutoOption.toAutoChangeScale` no longer controls if dpi-scaling takes places, this now happens automatically like in all other VCL controls. If this flag is set, the default node height and the header height are automatically scaled according to the used font. So far, the height was only increased to a minimum width so that the text is not cut off. But the height was never scaled down if the control was moved to a monitor with a smaller scaling. This now happens. See issue [#1206](https://github.com/JAM-Software/Virtual-TreeView/issues/1206).

> I tried to override this issue with setting toVariableNodeHeight 

You can override this by removing the `TVTAutoOption.toAutoChangeScale`.
