### ISSUE TITLE
Wrong canvas brush color in OnAfterCellPaint event

### ISSUE THREAD

**Issue by Dzyszla** [JAM-Software/Virtual-TreeView#1264]
If I set some color for TargetCanvas.Brush.color in OnBeforCellPaint event - all is ok. If I not, the background is valid (main color of component), but in OnAfterCellPaint the color of brush of TargetCanvas is GridLineColor, not main color.

![obraz](https://github.com/user-attachments/assets/7d2e2f6b-c42e-402b-bc87-9281c8c100e6)

```delphi
procedure TfrmMainCrm.vstDokBeforeCellPaint(Sender: TBaseVirtualTree; TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex; CellPaintMode: TVTCellPaintMode; CellRect: TRect; var ContentRect: TRect);
var
	pInfo: TInfoPozycja;
begin
	inherited;
	if Node = nil then
		exit;
	pInfo := vstDok.GetNodeData<TInfoPozycja>(Node);

	if pInfo.xCzyRoot then // sprawa
	begin
		TargetCanvas.Brush.Color := clInfoBk;
		TargetCanvas.FillRect(CellRect);
	end;
	if pInfo.xPrzypisany then
	begin
		TargetCanvas.Brush.Color := $00D7ECD7;
		TargetCanvas.FillRect(CellRect);
	end;
end;

procedure TfrmMainCrm.vstDokAfterCellPaint(Sender: TBaseVirtualTree; TargetCanvas: TCanvas; Node: PVirtualNode; Column: TColumnIndex; CellRect: TRect);
var
	pInfo: TInfoPozycja;
begin
	inherited;
	if Column = 13 {etykiety} then
	begin
		TargetCanvas.FillRect(CellRect); // -> I expect default color, but got gridline color background       
		pInfo := vstDok.GetNodeData<TInfoPozycja>(Node);

		uEtykiety.TEtykiety.Draw(TargetCanvas, CellRect, pInfo.Etykiety, pInfo.HintMap);
	end;
end;
```

**Comment by joachimmarder** [comment]
Please respect our guidelines on the project homepage for submitting bugs. Please include your version of Virtual TreeView and Delphi, and attach a sample compiling project as ZIP to your report that allows to replicate the problem. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug. If you already have a solution, please supply a patch file.

**Comment by Dzyszla** [comment]
Newest VST - 8.0.3
Sample project in attachment.
[VST_2.zip](https://github.com/user-attachments/files/16706223/VST_2.zip)

I didn't notice it in the 7.x version.

**Comment by joachimmarder** [comment]
If you want something to be drawn in a certain color in some custom draw event, it is always a good idea to set this color before drawing instead of relying that a certain color might be active when the event handler is called.

I guess the active color in the `OnAfterCellPaint` event currently depends on what was drawn before, which again depends on various options of the Virtual TreeView.

We can now discuss if the Virtual TreeView should set a certain color before calling the `OnAfterCellPaint` event. I don't think that makes much sense, since >99.9% of the code is setting a color or brush anyway. If we would do so, the interesting question is, which color should be active when calling after draw event? The color of the font? The color of the grid lines?

**Comment by Dzyszla** [comment]
But my intention is for the background to be "transparent", meaning it should have the color that is default in a given situation (standard background, highlighted, focused). I have no simple access to this color.

As I wrote - In the 7.x (check on 7.6.2) version the brush color was "default" and all looks good. After update to 8.x default brush color take over grid line color.

This make the difference:
`VirtualTrees.BaseTree.pas`, line 20627, in `TBaseVirtualTree.MoveTo` procedure:
```delphi
if not CellIsTouchingClientRight or ColumnIsFixed then
begin
  if (BidiMode = bdLeftToRight) or not ColumnIsEmpty(Node, Column) then
  begin
   DrawGridVLine(PaintInfo, CellRect.Top, CellRect.Bottom, CellRect.Right - 1, ColumnIsFixed and (NextColumn >= 0)); // << This is now
//    DrawDottedVLine(PaintInfo, CellRect.Top, CellRect.Bottom, CellRect.Right - 1); // << This is previously version. If replace line above to this line from old version - works good.
  end; 

  Dec(CellRect.Right);
end;
```

**Comment by joachimmarder** [comment]
> I have no simple access to this color.

Do you really say that accessing `vstDok.Colors.BackGroundColor` is too complicated?

**Comment by Dzyszla** [comment]
Yes, because it is NOT simple background color. If I have complicated code in event onBeforCellPaint, I don't want repeat it in second event. Next, if node (or row) is focused, then I need get another color. So, event becomes very expensive and slowly.

It's will stay as real background for cell, not be changed to other color. So I think, the solution with set default background isn't right. IMO, the Draw Grid will not change the brush color or will restore it after work.

**Comment by joachimmarder** [comment]
After removing the patch I tried the attached sample project and could not see any problem.
