### ISSUE TITLE
Some questions about TVTVirtualNodeEnumeration and TVTVirtualNodeEnumerator

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#412]
_From [hard...@126.com](https://code.google.com/u/106885845935740948701/) on January 21, 2014 02:37:19_

1)i think the TVTVirtualNodeEnumerator.FCanModeNext is a spell error of FCanMoveNext

2) in the the TBaseVirtualTree.VisibleNoInitNodes: Are you sure the default value of ConsiderChildrenAbove is Ture?
  all of the other return-enumeration-function have a ConsiderChildrenAbove  default to False

3)I think the TVTVirtualNodeEnumeration.GetEnumerator's implementation is unsafe:

function TVTVirtualNodeEnumeration.GetEnumerator: TVTVirtualNodeEnumerator;
begin
  Result.FNode := nil;
  Result.FCanModeNext := True;
  Result.FEnumeration := @Self;  -->it is unsafe
end; 

because TVTVirtualNodeEnumeration is a record, it is possible it has a different life period with the TVTVirtualNodeEnumerator instance, e.g.:

function func1(ATree:TBaseVirtualTree):TVTVirtualNodeEnumerator
begin
  Result:=ATree.ChildNodes(nil).GetEnumerator;
end;

the second risk is two TVTVirtualNodeEnumerator instance share a TVTVirtualNodeEnumeration;

procedure proc1(ATree:TBaseVirtualTree);
var
  e1,e2:TVTVirtualNodeEnumerator ;
begin
  e1:=ATree.ChildNodes(nil).GetEnumerator;
  e2:=ATree.ChildNodes(nil).GetEnumerator;

  //use e1 here

  //use e2 here --> it will be a undefine behavior

end;

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=412_

**Comment by vincentparrett** [comment]
_From [hard...@126.com](https://code.google.com/u/106885845935740948701/) on January 20, 2014 08:19:45_

sorry, the  proc1 shoule like this:

procedure proc1(ATree:TBaseVirtualTree);
var
  e: TVTVirtualNodeEnumeration; 
  e1,e2:TVTVirtualNodeEnumerator ;
begin
  e:=ATree.ChildNodes(nil);
  e1:=e.GetEnumerator;
  e2:=e.GetEnumerator;

  //use e1 here

  //use e2 here --> it will be a undefine behavior

end;

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on January 22, 2014 11:29:40_

**Labels:** -Priority-Medium Priority-Low

**Comment by the-Arioch** [comment]
Part 1: Indeed! a very stupid thing - to be trivially fixed :-)

```
  TVTVirtualNodeEnumerator = record
  private
    FNode: PVirtualNode;
    FCanModeNext: Boolean;

```

[0001-Typo-fix-https-github.com-Virtual-TreeView-Virtual-T.patch.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/864407/0001-Typo-fix-https-github.com-Virtual-TreeView-Virtual-T.patch.txt)

**Comment by the-Arioch** [comment]
> because TVTVirtualNodeEnumeration is a record, it is possible it has a different life period with the TVTVirtualNodeEnumerator instance

Ain't sure if that is practically possible, except for specific synthetic tests. 
However AFAIR in some my code - for the sake of simplicity - I made both enumeration and enumerator the same entity, don't remember though whether that was record or interface...

Because, separation of enumeration and enumerator provides for some flexibility... that is almost never needed.

**Comment by joachimmarder** [comment]
> because TVTVirtualNodeEnumeration is a record, it is possible it has a different life period with the TVTVirtualNodeEnumerator instance

Class instances would have the same theoretical possibility. The only proper way to avoid this would be using ref-counted objects that implement `IEnumerable<T>` and `IEnumerable<T>`. But these interfaces have their own problems: http://stackoverflow.com/questions/10657475/implementing-list-enumerator-oftypet-in-delphi

So I am not sure if it makes sense to change this. Typo mentioned in (1) has been resolved.

**Comment by joachimmarder** [comment]
> e:=ATree.ChildNodes(nil);
> e1:=e.GetEnumerator;
> e2:=e.GetEnumerator;
> //use e1 here
> //use e2 here --> it will be a undefine behavior

Sorry, but I don't really get why this results in undefined behavior. `e1` does not change any data of `e2` or `e`.

**Comment by the-Arioch** [comment]
> But these interfaces have their own problems

No, those were not interfaces-and-enumerators, those were interfaces-and-generics.
I had a lof of problems with them and in the end i turned to never use Sprign24D code in production with XE2. Because it can give you a big glorious F-bomb when you need it the least.

I think (but did not tested) that enumerator implemented as non-generic interface would work pretty well. However, if we really want to strike out any potential for ..TORs and ...TIONs to have mismatched lifespans, then we just should merge then into the same single shared entity. Because next thing would be smething like "but if i would zero out the internal variables (references to one another) betweern interface-based ...TOR and ...TION, then they still might have different lifespans" and so forth.

----------

a bit of offtopic
1) see also small fix in fb77e8a16599eb73944ce131fc9c6cbc8151b967 - it matters when VTV is not added to IDE-global seach path
2) do you know if there is such a functionaliy out of the box in VTV ? https://groups.google.com/forum/#!topic/virtual-treeview/_nhGtfhxkrA

**Comment by the-Arioch** [comment]
I think he refers to

```
function TVTVirtualNodeEnumerator.MoveNext: Boolean;
begin
  Result := FCanMoveNext;
  if Result then
  begin
    FNode := FEnumeration.GetNext(FNode);
```

That is why i implemented my own enumerator=enumeration as a single record fulfilling both roles and returning itself as enumerator.

--------

One one hand i can agree, that whether you use compiler magic, you have to use it as it was intended to be used. That means here, you do not go low-level into manual management of those -tors and -tions. You jsut issue for-in loop and let compiler do its magic without interfering. That said, even eithout interference that magic is not always done right, like Delphi 2006 did not know classes might have virtual methods :-/

So the reporter indeed point to a very fragiel part of the implementation. However it might be argued that mere using the compiler magic implementation explicitly, via variables and method calls, outside of opaque for-in magical framework, perhaps that is undefined behaviour already.

> e:=ATree.ChildNodes(nil);

This line alone is undefined behaviour, perhaps.

> e1:=e.GetEnumerator;

And this is yet another U.B.

------------

Frankly, the fragility he points at might be fixed by removing one single character and changing another one.

```
function TVTVirtualNodeEnumeration.GetEnumerator: TVTVirtualNodeEnumerator;
begin
  Result.FNode := nil;
  Result.FCanMoveNext := True;
  Result.FEnumeration := @Self;
end;
```

FEnumeration should be converted into a COPY of enumeration record, not a POINTER to it.
And the issue would bne fixed, but at a price of more memory copying and heap allocations.

Whether that game, which looks like a quest for purism, is worth the candles i ain't sure.

-----------

The scenarios the reporter envisions might be drafted like that:

```
e:=ATree.ChildNodes(nil);
TThread.Enqueue( procedure
  var n: VTVNode;
  begin
      for n in e do ....;
  end );
for m in e do ....;
```

No we have two enumeratORs running over the same enumeratION and stealing nodes from one another. Due to race condition which of nodes would be fetched by which of loops is not predictable.
Worst of all, i am not sure who will remove E from the memory. Will it be end of the procedure, or any of the "compiler magic" loops. Anyway, we are heading into use-after-free. If the M-loop finishes first, then it exits the procedure and E variable gets destroyed anyway, either by m-loop or by the procedure it matters not. But the N-oop continues to run over the pointer to the now-destroyed E-variable.

I agree that this is an obvious way to shoot yourself in the foot. Still i am not totally convinced if it has any practical implications, as the only contract that compiler magic implementation is subject to, it is that very compiler magic. There is no any legitimate use for those methods and records outside of for-in statement anyway. And when one dives into lo-level, then it becomes the diver's responsibiltiy to keep compatibiltiy with the compiler implementation.

**Comment by joachimmarder** [comment]
> FEnumeration should be converted into a COPY of enumeration record, not a POINTER to it.
> And the issue would bne fixed, but at a price of more memory copying and heap allocations.

I like that idea and I think the price to pay is low compared to the stuff that typically happens when doing such enumerations.

**Comment by joachimmarder** [comment]
> No we have two enumeratORs running over the same enumeratION and stealing nodes from one another. 

But why? I couldn't find a place where the enumeratOR modifies the enumeratION explicitly or implicitly.

**Comment by the-Arioch** [comment]
the Arioch:  Please, read the very beginning of my prior comment, the one starting with a code snippet and few lines above and below it :-)

Joachim:  Well that doesn't help. Above you are writing "I think he refers to" which doesn't explain anything. Below you write how you typically do that, which also does not answer my question. In the code snippet only members of the enumeratOR are modified, the call to `FEnumeration.GetNext()` also does not seem to modify members of the enumeratION.

**Comment by the-Arioch** [comment]
> I think the price to pay is low compared to the stuff that typically happens when doing such enumerations.

what " *typically* happens with *such* enumerations " is hardly relevant, because the topic is about this specific enumerator and not smoe average total over all enumerators that one can find in the wild.

such a simple fix would trigger Heap Manager cal which is never free.

So, basically i see three correct approaches to it

1) do nothing. Decide that enumerators are ONLY meant to be used via for-in compiler magic and that any other use of it is prohibited. Maybe even explcitly prohibit it in comments, and even mark those implementing methods with warning-clause like "deprecated" or "library" or anything, but otherwise change no code.

2) implement both ...tor and ...tion as one single record providing both sets of methods and returning POINTER to itself in its `GetEnumerator` - but i aint sure Delphi compiler magic would work with ^record kind of enumerators. It definitely work with classes, being reference-enitity, but class are comparatively quite heavyweight. whether `GetEnumerator := @Self`  aproach would work with Advanced Records i never tried.

3) implement it normal way: all the relevant fields from ...tion should be turned into the fields of ...tor and once being born the ...tor should break any and all links to ...tion. This would add just few memory-move operations, and would not have any Heap allocations, thus would be much less expensive than the lazy "remove @" approach.

**Comment by joachimmarder** [comment]
> FEnumeration should be converted into a COPY of enumeration record, not a POINTER to it.
> And the issue would bne fixed, but at a price of more memory copying and heap allocations.

More memory needs to be copied and the size of the allocated memory is larger, but that shouldn't have any significant impact. There is no additional heap allocation to be done.

**Comment by the-Arioch** [comment]
Hmm.... Yep, you are probably correct here. 

Well, personally i would not consider this issue any important: my approach to it is option 1.
So... i would not invest my time into it :-D

**Comment by joachimmarder** [comment]
> i would not invest my time into it 

Given that, you invested a lot of time in writing comments on this issue.   :-)

But if there is not really an issue, there i no need to invest time in it and I will close it so that no one else wastes time on it.

**Comment by the-Arioch** [comment]
Comments do not break anyone's else code so do not have to be tested :-)

> the call to FEnumeration.GetNext() also does not seem to modify members of the enumeratION.

True, but then my second snippet matters - "use after free" :-D

**Comment by joachimmarder** [comment]
> FEnumeration should be converted into a COPY of enumeration record, not a POINTER to it.

That will most like not work, because both records reference each other, and you cannot forward declare records, like this is possible with classes.  That might be the reason why the approach with a pointer was used in the first place, which is the common solution to break such circular type references.
