### ISSUE TITLE
XE support for V6

### ISSUE THREAD

**Issue by vincentparrett** [JAM-Software/Virtual-TreeView#503]
_From [delphiso...@gmail.com](https://code.google.com/u/115057366770737659138/) on December 13, 2014 07:50:13_

I can see no reason to not support XE (maybe even 2010 as there are not many changes regarding that) in V6 anymore.

It is just a matter of some ifdefs for the VCLStyles related code. I managed to put them in a few minutes.

_Original issue: http://code.google.com/p/virtual-treeview/issues/detail?id=503_

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 14, 2014 12:50:15_

> I can see no reason to not support XE

There is a perfect and simple reason: So far no one volunteered to do it. 

> I managed to put them in a few minutes.

Sure, this is easy for a specific version if you are activly using it. Doing all the {$ifdef}s right for all the old versions when actually using XE7 has proven to be quite difficult and costs a lot of time.

If someone volunteers to do this in a separate branch, this will be fine.

**Labels:** -Type-Defect Type-Enhancement

**Comment by vincentparrett** [comment]
_From [delphiso...@gmail.com](https://code.google.com/u/115057366770737659138/) on December 14, 2014 15:10:10_

> There is a perfect and simple reason: So far no one volunteered to do it.

And yet someone put effort into removing the code for these versions.

Anyway I can let you have the diff file but I don't have time nor feel like maintaining an extra branch constantly because these changes can be done in the trunk without much effort because as I said regarding XE it only affects some themeservice/vclstyles related code.

**Comment by vincentparrett** [comment]
_From [joachim....@gmail.com](https://code.google.com/u/109917800154443778416/) on December 16, 2014 13:05:16_

> I don't have time nor feel like maintaining an extra branch constantly

I don't have time nor feel like maintaining the code for versions that I have not installed and cannot test against. I believe this should be done by someone who is actively using the version of Delphi.

**Comment by joachimmarder** [comment]
Since so far nobody volunteered to maintain V6 for Delphi XE, I will close this issue as WONTFIX.

**Comment by Fr0sT-Brutal** [comment]
I made a branch [here](https://github.com/Fr0sT-Brutal/VirtualTreeView_mod/tree/fr0st-xe2) and will try to maintain it until upgrade to newer XE.

**Comment by joachimmarder** [comment]
Is this branch RAD Studio XE only? Or does it also cover XE2?

**Comment by romankassebaum** [comment]
I would create a branch for very Delphi version so that there is no need to use defines. I also would push this branches to the Virtual-TreeView organization.

**Comment by Fr0sT-Brutal** [comment]
@joachimmarder I tested with XE2 only but AFAIR there was no specific compiler changes in XE and XE2 so it should work even on 2010.
@romankassebaum I posted that link in google code issues but devs seemed not being interested in supporting older versions so I didn't insist.
Talking about branches, well... currently there's too little changes must be made to support pre-XE3. I doubt they worth personal branch. But OTOH this would follow the V5 way. IDK, it's up to devs to make decision.

**Comment by romankassebaum** [comment]
If it is okay for you then I will push your branch to
https://github.com/Virtual-TreeView/Virtual-TreeView XE2

Then others that would like to work with XE2 will find it easily.

**Comment by Fr0sT-Brutal** [comment]
No problem but hold on until I update it to the current upstream (otherwise you'll have to apply patches manually)

**Comment by romankassebaum** [comment]
Please tell me when I can start.

**Comment by joachimmarder** [comment]
> I posted that link in google code issues 

Sorry, I didn't see this link. Where did you post it? We imported all Google Code issues to here.

**Comment by Fr0sT-Brutal** [comment]
@joachimmarder from what I remember, I created a special issue called "VTV for XE2" or something similar. Google seem to export only a part of the issues because I tried to find all the subjects I posted to but found only few.
@romankassebaum I completely reworked the repo and redesigned modifications. In fact I declared missing `TStyleElements` and `StyleElements` so the number of ifdefs has been significantly reduced. The branch is ready at https://github.com/Fr0sT-Brutal/VirtualTreeView_mod/tree/fr0st_xe2

**Comment by romankassebaum** [comment]
I pushed your repo to
https://github.com/Virtual-TreeView/Virtual-TreeView-XE2.git

Now he have an official XE2 branch. :-)

Many thanks for your help!

**Comment by Fr0sT-Brutal** [comment]
You're welcome but are you sure you made it right? You've created a separate repo, not a branch. It has only 1 branch and doesn't contain my commit. I thought you'll make a branch just like it was done for V5 so that I could pull and merge the changes (or you could do it yourself by `git checkout <XE2branchname> && git merge master`)

**Comment by romankassebaum** [comment]
I created a repo with the same root, this is a named branch. Git allows me to push changes from the main branch to the named branch. This one way to work with branches.

I haven't looked at your repo but did you commit your changes to the main branch in your repo?

**Comment by Fr0sT-Brutal** [comment]
Well, it's kinda weird way to work with branches. Why do you dislike creating a branch in the main repo?
I committed changes to special branch "fr0st_xe2" because my repo is a fork of yours so master branch mustn't be modified.

**Comment by romankassebaum** [comment]
I'm working internally with HG and Kiln. It handles branches perfectly.

Working with branches in the main repo makes it difficult to switch between HG and GIT, e.g. "main" is called "default" in HG.

**Comment by Fr0sT-Brutal** [comment]
Certainly you can do it as you like but with this config I won't be able to report changes. If XE2 version was a branch of main repo which I'd forked I could easily prepare and post pull request. Now I just update my own repo (just fixed `VirtualTrees.Actions` uses section - XE2 has no `System.Actions` unit) and it's up to you to track changes.

**Comment by romankassebaum** [comment]
Maybe you misunderstood what I'm doing. The XE2 version is a branch of the main repo.

I give you an example. Under TurboPack (https://github.com/TurboPack) we are hosting some Delphi and C++Builder components that only support the current RAD Studio version, over and out.

But there is a guy who wants to use one component, Orpheus, for XE5. That's why I created a new organization (https://github.com/TurboPack-XE5)  and a new branch for Orpheus (https://github.com/TurboPack-XE5/Orpheus).

The XE5 branch is a real branch, you can push and pull changesets in both directions. In practice, we will only move changesets from the main branch to the XE5 branch.

We can also work with all preferred tools like git, hg, kiln, tortoisehg, tortoisegit and beyondcompare.

And I want to do the same with the VT and XE2. The main version only supports XE3 and better. For XE2 we can create a branch.

Now, you should create a named branch (This is how hg calls it), a branch (This is how kiln calls it) or a fork (This is how github calls it). Then you should commit your changesets to the main (for git) or default (for hg) branch in your local repo. At the end we should push it to the XE2 github fork.

If Joachim gives you sufficient rights you can do the pushing stuff yourself, otherwise I can do it for you.

**Comment by Fr0sT-Brutal** [comment]
You already have V5 branch (in git terms) in the main repo, what's the sense in creating one more repo? But if you do not mind updating XE2 repo after every commit to the main one I could start using it instead.

**Comment by joachimmarder** [comment]
Has this been sorted out? 

Giving the person who volunteers to maintain the V5 branch write access to this branch makes sense to me now that V6 is officially out.

**Comment by Fr0sT-Brutal** [comment]
I don't know what we decided finally. As for me, separated repo is inconvenient. But if Roman will update it from this one, I'll link to it and will update modifications when needed.

**Comment by romankassebaum** [comment]
It is not a separated repo it is a fork. Having XE2 code in the official repo is for me a no go.
But I will stop arguing at this point.

**Comment by joachimmarder** [comment]
There is meanwhile an XE and XE2 compatible branch maintained by @sglienke at:
https://github.com/sglienke/Virtual-TreeView
