### ISSUE TITLE
Problem with SetFocus

### ISSUE THREAD

**Issue by mauxion2** [JAM-Software/Virtual-TreeView#531]
Using TreeView->SetFocus() in TreeViewMouseEnter
void __fastcall TreeViewMouseEnter(TObject *Sender)
{
  TreeView->SetFocus();         // automatically close editing
}
When editing a node by pressing F2, move cursor mouse to rectangle editing is automatically close editing.
When the silent entry setfocus it works properly
void __fastcall TreeViewMouseEnter(TObject *Sender)
{                          // editing work properly
 }

**Comment by joachimmarder** [comment]
I guess this is by design, e.g. the VCL TTreeView and TListView behaves the same.

Either call SetFocus() in the OnEditing event, or use a condition:

if not TreeView.IsEditing then TreeView.SetFocus()

Please do not open issue to get support. Please try to get support from the community e.g. at Stack Overflow , Delphi Pages, or Embarcadero forums. Once you verified that you found a real bug, then open the issue.
