### ISSUE TITLE
V5 stable warning "Unsupported language feature: 'class constructor'"

### ISSUE THREAD

**Issue by bustercopley** [JAM-Software/Virtual-TreeView#543]
As mentioned in passing in #538, building the "V5_stable" branch on XE2 gives warnings:

Compiling VirtualTreesR.dproj (Release, Win32)
[DCC Warning] VirtualTrees.pas(1): W1025 Unsupported language feature: 'class constructor'
[DCC Warning] VirtualTreesR.dpk(46): W1025 Unsupported language feature: 'class constructor'

The same warnings were the subject of issue #346, fixed in SVN r519 (2013-07-11). The warnings were reintroduced in SVN r734 (2014-10-11) which refs issue #479.

If I understand it correctly, the warning is issued because, although class constructors and destructors are supported in Delphi since Delphi 2010, they are not supported in C++ builder (See QC #113891). The default in the VT project files is to build the C++ builder output files.

Any chance of revisiting this?

**Comment by joachimmarder** [comment]
As far as I know class constructors are supported in C++ Builder, just the C++ Builder linker lacks the ability to remove the class constructors of unused classes from the binary. So not a big problem.

Since this warnings caused frequent question and opened issue, I changed this again in V6 and so consider this issue as fixed.
