### ISSUE TITLE
FullRowSelect not correct 

### ISSUE THREAD

**Issue by MstrVLT** [JAM-Software/Virtual-TreeView#550]
Selection row by click over bounds columns (Column=NoColum), not work.
Problem in 22283 line (hiNowhere not needed)

**Comment by joachimmarder** [comment]
To which version does this issue report apply? V6.0 or GIT master?

**Comment by MstrVLT** [comment]
6.0
the mistake is here: 
IsCellHit := not AltPressed and not IsLabelHit and Assigned(HitInfo.HitNode) and
    ([hiOnItemButton, hiOnItemCheckBox] \* HitInfo.HitPositions = []) and
    ((toFullRowSelect in FOptions.FSelectionOptions) or
    ((toGridExtensions in FOptions.FMiscOptions) and (HitInfo.HitColumn > NoColumn)));

**Comment by joachimmarder** [comment]
The description of this report consists of less than one line and I am not sure what it means. Please follow the guidelines on the GitHib homepage for submitting bugs:

" When reporting a bug please include a sample project that allows us to quickly reproduce the bug. This can also be one of the demo projects that come with Virtual Treeview, modified to show the bug. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug. If you already have a solution, please supply a patch file."

If the Virtual TreeView behaves similar to the Explorer right pane of the Windows Explorer, the behavior maybe be intended. The code looks OK to me:

```
TVTHeaderHitPosition = (
hhiNoWhere,         // No column is involved (possible only if the tree is smaller than the client area).
```

So if hiNoWhere is set, no column is involved. However a cell requires a column, so IsCellHit should not be True in case hiNoWhere is set.
