### ISSUE TITLE
VirtualTrees.StyleHooks is missing the un-registering of StyleHooks

### ISSUE THREAD

**Issue by NickRing** [JAM-Software/Virtual-TreeView#591]
VirtualTrees.StyleHooks is missing the un-registering of StyleHooks, which means that when used within a DLL that gets loaded and unloaded, unusable StyleHooks still registered that could crash the application.

Currently, VirtualTrees.StyleHooks.pas looks like this.

```
initialization
  TCustomStyleEngine.RegisterStyleHook(TVirtualStringTree, TVclStyleScrollBarsHook);
  TCustomStyleEngine.RegisterStyleHook(TVirtualDrawTree, TVclStyleScrollBarsHook);
```

It should be like this:

```
initialization
  TCustomStyleEngine.RegisterStyleHook(TVirtualStringTree, TVclStyleScrollBarsHook);
  TCustomStyleEngine.RegisterStyleHook(TVirtualDrawTree, TVclStyleScrollBarsHook);

finalization
  TCustomStyleEngine.UnRegisterStyleHook(TVirtualStringTree, TVclStyleScrollBarsHook);
  TCustomStyleEngine.UnRegisterStyleHook(TVirtualDrawTree, TVclStyleScrollBarsHook);
```

**Comment by joachimmarder** [comment]
The calls to UnregisterStyleHooks() were once there, they however needed to be removed due to strange problems that most likely originated in the VCL. The issues were #355 and #359, but for unknown reasons these issues were not imported from Google Code to GitHub. The appropriate changes were made in commit 918abdb .

But of course the code change you propose is formally correct. I will apply it. In case problems are being reported again, I will surround the code in the finalization part with an `if IsLibrary then` which should still do the trick for you.

**Comment by NickRing** [comment]
Sounds like a plan - Thanks!
