### ISSUE TITLE
Before using SetTimer, check for valid WindowHandle

### ISSUE THREAD

**Issue by Memnarch** [JAM-Software/Virtual-TreeView#595]
Whereever SetTimer is used, it must be ensured to check if the WIndowHandle is valid.

Example: (VirtualTrees.pas, Line 18233, as of 7. December 2015)

``` Delphi
procedure TBaseVirtualTree.Change(Node: PVirtualNode);

begin
  AdviseChangeEvent(False, Node, crIgnore);

  if FUpdateCount = 0 then
  begin
    if (FChangeDelay > 0) and not (tsSynchMode in FStates) then
      SetTimer(Handle, ChangeTimer, FChangeDelay, nil)
    else
      DoChange(Node);
  end;
end;
```

if i set ChangeDelay to early (like in contructor of a derived class), and i do some changes which trigger the OnChange normally, they'll be ignored. At such moments, WIndowHandle is not allocated, and NULL is passed as parameter to SetTimer (which changes the behavior of it, and expects a callback instead). For my usecase i did this simple change, which means that no delay occurs until the window has been allocated:

``` Delphi
procedure TBaseVirtualTree.Change(Node: PVirtualNode);

begin
  AdviseChangeEvent(False, Node, crIgnore);

  if FUpdateCount = 0 then
  begin
    if HandleAllocated and (FChangeDelay > 0) and not (tsSynchMode in FStates) then
      SetTimer(Handle, ChangeTimer, FChangeDelay, nil)
    else
      DoChange(Node);
  end;
end;
```

**Comment by joachimmarder** [comment]
GetHandle() creates the handle if needed (and possible). Simply adding the condition HandleAllocated before every call of SetTimer() could change the behavior of the Virtual TreeView control. 

In the case you are referring to this i perfectly save because there is an else-case which should do what's necessary. 

Most cases in which SetTimer() is used are part of processing Windows messages, we can be sure that the handle exists here because without a handle we would not receive messages.

The only remaining use of SetTimer() in which we cannot be sure that a handle exists is in TBaseVirtualTree.StructureChange(). I solved this accordingly to TBaseVirtualTree.Change().

**Comment by Memnarch** [comment]
Thanks :)
EDIT: just something to keep in mind: if no window is already existing and you force to create one at your timing, it might be recreated at a later time when controls are parented. Timers get lost.
