### ISSUE TITLE
Virtual nodes and variable height

### ISSUE THREAD

**Issue by Mikanoshi** [JAM-Software/Virtual-TreeView#601]
If I'm understanding correctly... It is not possible at all to init root nodes only when they are needed and not possible to do the same with child nodes that have variable height? They all are initialized immediately. Any way to use TVirtualDrawTree to draw a list that has only 1 level (at least visually)?

**Comment by joachimmarder** [comment]
Please do not use GitHib Issues for support question. Please try to get support from the community e.g. at Stack Overflow , Delphi Pages, Delphi Praxis or Embarcadero forums.

In order to display correct scrollbars, the height for all root nodes needs to be known if their height is variable. You may still initialize parts of your structures deferred if you don't need them to provide the node height.
