### ISSUE TITLE
Remove property `CheckImageKind`

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#622]
This idea was inspired by a comment on issue #585. On high dpi systems the checkbox images `TCheckImageKind.ckLightCheck .. TCheckImageKind.ckXP` don't look good because they come from static 16x16 pixel bitmap resources. 

The images for  `TCheckImageKind.ckSystemFlat` and `TCheckImageKind.ckSystemDefault` are generated using the API call `DrawFrameControl()`, I think these are the checkbox images of the Windows classic style (the Windows 2000 style). They look different from those used e.g. for the `TCheckbox` control. 

I would like to propose removing the property `CheckImageKind` because I don't see the point in maintaining various sets of custom checkbox images for Virtual TreeView in times of Windows themes and VCL styles. The property CustomCheckImages would still allow using own custom checkbox images. 

Comments are welcome.

**Comment by blikblum** [comment]
I think is a good move. 

In order to minimize the work for those that need the current image based checkimage kind a VTCheckImages unit could be provided with them.

**Comment by joachimmarder** [comment]
Property `CheckImageKind` is still there to prevent errors in the IDE when opening existing forms, but it is no longer stored in DFM files. This will simplify its removal in a later version. The only remaining valid values in the enum are `ckSystemDefault` and `ckCustom`.

**Comment by the-Arioch** [comment]
:-/ 

So, how the system with updated VTW is going to load OLD DFM,s that still had all kind of values for now but removed property  CheckImageKind  :-/

Sad, I did not saw it earlier...

Problem - bad one - with reducing properties is that old values are still there in DFMs and DFMs are perfectly compiled! But on runtime they are crashed!

One has to make compatibility stubs to load old-format DFMs no matter how old those values are.
http://docwiki.embarcadero.com/Libraries/Berlin/en/System.Classes.TComponent.DefineProperties

**Comment by joachimmarder** [comment]
> Sad, I did not saw it earlier

Well, it was clearly marked on top of the Changes.txt:

``` 
V6.4: (28 Sep 2016)
* Fixed #622: [BREAKING CHANGE] Removed all 16x16 fixed sized checkbox-imagelists.
   The property CheckImageKind supports the values ckSystemDefault and ckCustom only and should be considered deprecated.
```

> One has to make compatibility stubs 

Good idea, never came across this trick so far. Reader and writer would be empty dummy methods then?

**Comment by the-Arioch** [comment]
take this patch
it fixes the issue

breaking backward compatibility in the way that can not be found in compile-time was a questionable thing... Even if there is a some fine print about it here and there.

[0001-Fixing-DFM-loading-runtime-crash-introduced-by-https.patch.txt](https://github.com/Virtual-TreeView/Virtual-TreeView/files/858900/0001-Fixing-DFM-loading-runtime-crash-introduced-by-https.patch.txt)

**Comment by the-Arioch** [comment]
Was there a question in the maillist before that change was commited? request for comments how to do it without killing compatibility? cause I tried to look into maillist even if I did not followed GIT

> never came across this trick so far. 

Despite VTV itself used it at least thrice... :-/

> would be empty dummy methods then?

Hell no!!! Reader should skip exactly so many bytes how the property value body in the stream has.

**Comment by joachimmarder** [comment]
Thanks for the patch. But why the `{$IfOpt D+}` part?

**Comment by the-Arioch** [comment]
Because that was not the knowledge at the fingerprints, I had to recall how to do it and then check the intimate intricacies of it. So I kind of worry about a future maintainer of it (me or anyone else - no matter)

I mean, imagine if few months/years from today it would suddenly stop working after some another RTL change. How would you manage to fix it then?

This part provides for two things with one shot
1) it keeps Release-compiled code lean, without any non-needed hassle.
2) it keeps Debug-compiled code ready to be debugged, there is both self-documenting of intentions and place to put a breakpoint and compare actually reported by RTL values with expected by initial developer.

**Comment by joachimmarder** [comment]
> Was there a question in the maillist before that change was commited

Do you mean that Google Group? I don't think so, it is not much used since we moved away from Google Code. All discussion takes place in the issues and code reviews. This one also was open for a while tagged as "Open for discussion".

**Comment by joachimmarder** [comment]
>it keeps Debug-compiled code ready to be debugged, there is both self-documenting of intentions and place to put a breakpoint and compare actually reported by RTL values with expected by initial developer.

I learned to hate `$IF`s and `$IFDEF`s in the code: The more you have, the more difficult it is to make sure all combinations compile and work correctly, which was one important reason to drop support for old Delphi versions. I don't seen why this `$IF` should stay in the code once it is finally tested.

**Comment by the-Arioch** [comment]
> Google Group.... is not much used since we moved away from Google Code
Not a bug but a feature. It then could be used for really important questions, standing our of regular mundane noise bug tracker is :-)
 
> This one also was open for a while tagged as "Open for discussion".

That is it, one has to read all through the tracker to filter those issues, but sometimes one does not want or can not to indulge that much...

> The more you have, the more difficult it is to make sure all combinations compile and work correctly

There are cons and pros, certainly. Especially when there are *combinations* of orthogonal options, which can be switched with no limitation from one another.
Less so with linear lists Delphi versions are - there is no *combinations*.
Even less, with a small isolated snippet.

Look, i am working with a legacy project, spaghtetti full of circular dependencies, and some source units were compiled differently, whether they went into this DLL, that DLL, or EXE - specifically to delete class members that would not get compiled without other modules(and their dependencies), that were left out in this or that DLL.
So i can feel your pain. 

It is like this *with* holy war - the operator can ease and stabilize things greatly when used in small isolated snippets, or might ruing all the code when vastly overused. Same with lambdas, too.

So, while i am not a big fan of conditional compilation mysef, i also has no zeal for total eradication of those. You will have to reflect different versions in you code, just instead of IfDef's you would use other means of it. But in the end of the day 0 that would be the same complexity.

That was vast difference between Delphi versiosn that hurt you, not *IfDef*s themseves.
Did you considered supporting all the same Delphi versions line-up just without conditional compilation? 
See, it is complexity itself - vast Delphi difference - that matters, not the tool - IfDef or other - that deals with it.

Granted, parts of IDE are badly failing with IfDefs too, like Form Designer, class completino sometimes, DPROJ XML management forms, etc. So i think i do know where you're coming from.

> I don't seen why this $IF should stay in the code once it is finally tested.

Because it may cease working in the future OSes and Delphis. Because "tested" is somewhat vague word, akin to that "works on my machine" quality seal - the assumption might prove wrong with other users than me.

I do not insist you keep it like that though, i outlined my reasoning which might be convincing or not. You can comment it out, leaving it merely as passivated text. Or remove alltogether, that is your repo and your choice. Also, code is not the only docuumentation, you may chose to introduce separate dedicated  "design documents", or just delete any reasoning of it.

I used that my code to check my asusmptions, they proved correct so i could start with typing Release code. NOW i know it would work from starters. But back then i was NOT that sure. So the very information about "intentions, expectations and methods to debug" have value, i think. And are worth keeping even if seen as clutter. Afterall, debug hooks always were and will be clutter. But that is MY own gut feeling, nothign more.

**Comment by joachimmarder** [comment]
>Granted, parts of IDE are badly failing with IfDefs too, like Form Designer, class completino sometimes, DPROJ XML management forms, etc. So i think i do know where you're coming from.

Hell yes.

> Because it may cease working in the future OSes and Delphis. Because "tested" is somewhat vague word, akin to that "works on my machine" quality seal - the assumption might prove wrong with other users than me

Well, understand your idea. But I would go down that road here only if I generally would use that approach. But then I would end up in a `$if` hell (again). In the end you can boil this code down to one assertion and avoid "value assigned to s is never used" warnings. Assertion are nice because they are typically not compiled in release builds, but do not need `$if`s

**Comment by the-Arioch** [comment]
Assert may do to, just gives no variables to put breakpoint for checking, unless one would debug it in CPU assembler window :-D

> But then I would end up in a  $if  hell (again). 

Nope. It is like saying that using while loops once you had to end up using while loops everywhere instead all the loop kinds, and that using case makes you end never using if-then-else. Nope. A tool is just a tool, you can always keep it in a limited place :-)

**Comment by the-Arioch** [comment]
BTW, did you try to compile it in {$T+} typed @-pointers mode?
Because I see one change in my sources: `procedure TBaseVirtualTree.SetNodeData ... NodeData := pointer(@pNode.Data)` - which explicit typecasts normally fixes compilation for strict pointer type checking issues

**Comment by joachimmarder** [comment]
> did you try to compile it in {$T+} typed @-pointers mode?

That code was that way for years. I just fixed it using an explicit cast to type `PPointer` from `System` unit. Hopefully this type already existed in XE2/XE3.

**Comment by the-Arioch** [comment]
PPointer is also typed, that is why I preferred to use explicitly untyped Pointer

**Comment by the-Arioch** [comment]
http://docwiki.embarcadero.com/Libraries/XE2/en/System.PPointer

Good news: http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/delphivclwin32/System_PPointer.html
Not so good news: http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/delphivclwin32/ObjAuto_PPointer.html

**Comment by joachimmarder** [comment]
> PPointer is also typed, that is why I preferred to use explicitly untyped Pointer

But you asked about the strong type @-operator mode?!?
It is a local variable only, so it should not affect your code.

**Comment by the-Arioch** [comment]
yep, I already merged it
