### ISSUE TITLE
Wrong hot node selection during mouse movement over different nodes.

### ISSUE THREAD

**Issue by jampeter** [JAM-Software/Virtual-TreeView#626]
If you move the mouse quickly from one node to another one, the selected hot node is incorrect in some cases.
Steps to reproduce:
Use the 'Minimal'  virtual treeview demo project.
Replace the Main.dfm:
[Main.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/636047/Main.zip)

or
open the project and
1. Create a TVTHeader column.
2. Change the following options:
   a. HintAnimation: any value except hatNone
   b. HintMode: hmTooltip 
   c. ShowHint: true
   d: TreeOptions -> PaintOptions: toHotTrack and toUseExplorerTheme: true
3. Run and move quickly over some nodes. If you stop, a wrong hot node is selected in some cases. 

Maybe similar to this bug:
https://github.com/Virtual-TreeView/Virtual-TreeView/issues/452

**Comment by sanjayssk** [comment]
>>Replace the Main.dfm with this one
I can't download this. The link goes to a "spammy" looking site with bogus download buttons. The real download button does not work. They probably want you to click other buttons for ad revenue. Please use some other site to provide your sample.

Thanks.

**Comment by jampeter** [comment]
> Replace the Main.dfm with this one
I can't download this. The link goes to a "spammy" looking site with bogus download buttons. The real download button does not work. They probably want you to click other buttons for ad revenue. Please use some other site to provide your sample.

I have replaced the link in the Bug description by a link on github.

**Comment by sanjayssk** [comment]
Got it. Thanks.

**Comment by sanjayssk** [comment]
@jampeter 
Question: Did you find this problem in your own application and then made the steps to reproduce in Minimal Demo or did you directly use Minimal demo to experiment and found this bug? I'm asking because Minimal Demo had a major problem in DFM which is there in your DFM too.

I'm not able to reproduce this problem. Correct node is always selected. 

I suggest, you try this:

- Check out the latest Minimal Demo

- Merge your DFM changes but leave out **RootNodeCount** as that is wrong.

- Additionally, switch off the Selection Option: **toCenterScrollIntoView**. If this is left ON, it causes confusion because the selected node is moved to the middle of the tree and it might give the impression that a wrong node was selected.

Now see if you can reproduce the same problem. Please let me know. 

Thanks.

**Comment by jampeter** [comment]
Hi!
I found this problem in my own application and then made the steps in the demo. I can still reproduce the problem with the latest demo by using the manual steps described above (without the attached dfm).  I also disabled toCenterScrollIntoView but the behaviour didn't change. One thing I recognized is that the issue only occurs when the tooltips pop up while moving the mouse up and down on the column.
I have attached a new [Main.dfm](https://github.com/Virtual-TreeView/Virtual-TreeView/files/645370/Main.zip) which is created with the latest minimal demo and the manual steps above (Delphi XE10 upd 2). The RootNodeCount seems no longer present in the dfm but the problem still exists. Just replace tthe minimal demo dfm whith this one, start the app and quickly move the mouse up and down over the first column a few times, then stop and in most cases a wrong node is selected.
Best regards

**Comment by sanjayssk** [comment]
I have debugged this in detail. Here are some observations:

- When you stop and a wrong node is highlighted for hot track, if you just wait without moving the mouse, after some delay, the correct node is selected.
- The above delay is equal to the time that the animated hint stays on the current node.
- I have tried all sorts of things to make this delay go away but no luck. Basically, the mousemove causes these hottrack highlights and somehow the mousemove for the latest node is not processed till after the animation.
**Conclusion:** So I would suggest that hint animation should not be used with hot tracking. But it's difficult to enforce in design interface. Instead, I can change the code internally so that if hot tracking is being used, it will avoid the animation and will do a straight hint.

**Comment by joachimmarder** [comment]
Your conclusions sound good to me. I think we shouldn't invest too much time in this issue.

**Comment by jampeter** [comment]
Yes, I think the conclusion is sufficient in most cases. Thank you for investigating this error.

**Comment by sanjayssk** [comment]
Thank you for confirming. Fixed and closed.
