### ISSUE TITLE
[Feature Request] VisibleNode Index Property

### ISSUE THREAD

**Issue by LordNullPointer** [JAM-Software/Virtual-TreeView#634]
VirtualTreeView should get a readonly property to receive the VisibleIndex of a specific node. The visible index of the node should be counted from top to bottom. So it needs to be counted when the program needs this information. It should also consider the nodes in deeper levels, but only if they're visible.

This feature is required if you want to paint an alternating color for the rows and maybe in some other cases too.

```
1 - Node
2 - Node
3    L Node
        L Node (not visible)
4 - Node
```

`property VisibleIndex[Node: PVirtualNode]: Cardinal read GetVisibleIndex;`

Maybe the procedure could look like this if there's no better way to do so. This is currently my workaround in the OnBeforeCellPaint Event.

```
function GetVisibleIndex: Cardinal;
var
  PreviousNode: PVirtualNode;
begin
  PreviousNode := Sender.GetFirstVisible;
  Result := 0;
  while (Assigned(PreviousNode) and (PreviousNode <> Node)) do begin
    Inc(Result);
    PreviousNode := Sender.GetNextVisible(PreviousNode);
  end;
end;
```

If this feature request isn't clear enough, feel free to ask.

**Comment by joachimmarder** [comment]
> The visible index of the node should be counted from top to bottom.

Should it be counted from the very first node, or from the first node in the currently visible scroll area? The latter could be faster, but a node would change its VisibleIndex 

> Maybe the procedure could look like this

The suggested code is a little slow if a lot of nodes are visible in the tree, because it always starts iterating from the beginning. For painting rows in alternating colors the complexity is `O(n*m)` where `n` is the number of visible nodes and `m` the number of rows that fit in the control.

**Comment by LordNullPointer** [comment]
I think it would be ok to take the first partially visible node to be the first index, starting with 0. Another possibility would be, to make two properties. First one would be AbsoluteVisibleIndex (Counting from the very first node) and the second one is VisibleIndex oder EffectivelyVisibleIndex (Counting from the first partially visible node).

I thought that this code wouldn't be the best way to count the index. It's only my current workaround to get the things working.

**Comment by sanjayssk** [comment]
I think it needs some reverse thinking. Why didn't the original designer think of such a property? Maintaining such index properties on a node is a expensive on processing because each insertion, move or deletion will have to iterate the tree to fix visible indexes of other nodes which defeats the purpose of the tree structure in the first place. It is similar to the concept of a linked list data structure where the whole purpose of the structure is to maintain a sequence, yet be efficient to insert, move or delete. That's the reason such properties are not there in the original design and shouldn't be there. The only such property which was put in there for the node is TotalCount and you can see that it has to carry the burden of the functions AdjustTotalCount and FixupTotalCount. 

The best way to solve these problems is by custom code similar to what you already wrote in a derived class or helper function. But to make it more efficient, start from the TopNode and end at BottomNode so that only the nodes visible on the screen are iterated.

**Comment by joachimmarder** [comment]
> First one would be AbsoluteVisibleIndex (Counting from the very first node) and the second one is VisibleIndex oder EffectivelyVisibleIndex (Counting from the first partially visible node).

It would be extremely costly to maintain those properties.

**Comment by joachimmarder** [comment]
> This feature is required if you want to paint an alternating color for the rows

For this specific feature issue #224 already exists. I don't think we need this issue in addition. The proposed solutions have too strong impacts if not used.
