### ISSUE TITLE
MemoryLeak in VirtualTrees.ClipBoard

### ISSUE THREAD

**Issue by landrix** [JAM-Software/Virtual-TreeView#648]
after the last changes, you should add

finalization

  if _List <> nil then
    TClipboardFormatList.Clear;
  FreeAndNil(_List);

to prevent memleaks.

Why do you moved _List from Class Var to a local Var?

**Comment by joachimmarder** [comment]
> `TClipboardFormatList.Clear;`

Calling `Clear()` should not be necessary because `TList.Destroy()` calls Clear(), and `FreeandNil()` calls the destructor.

> Why do you moved _List from Class Var to a local Var?

Because I can do initialization outside the scope of the initialization section, this is what #642 was about. A global variable is initialized with `nil` autmatically: http://stackoverflow.com/questions/132725/are-delphi-variables-initialized-with-a-value-by-default

Delphi calls class constructors as part of the initialization section.

**Comment by landrix** [comment]
Without clear, the Strings in the record leaves in memory. I think, clear from list is not enough.i've checked this with fastmm4. I had never looked at this, if there is no leak.

**Comment by joachimmarder** [comment]
Sorry, you are right. I missed the fact that the list stores Pointers to records, and not records or objects. I think would change that and do that using a generic list.
