### ISSUE TITLE
VK_BACK + edit

### ISSUE THREAD

**Issue by ghost** [JAM-Software/Virtual-TreeView#650]
VK_BACK in an editable cell with no parent => edit/clear
VK_BACK in an editable cell with parent => navigate to parent

**Comment by joachimmarder** [comment]
Which version of Virtual TreeView are you using?

The bug report is very brief. Please respect our rules for submitting bugs written on the [homepage](https://github.com/Virtual-TreeView/Virtual-TreeView):

First of all, please make sure you are using the latest official version. When reporting a bug please include a sample project that allows us to quickly reproduce the bug. This can also be one of the demo projects that come with Virtual Treeview, modified to show the bug. If only small changes are required, a description is sufficient how a demo projects needs to be changed in order to replicate the bug. If you already have a solution, please supply a patch file or make a pull request.

**Comment by ghost** [comment]
Sorry about that...
Version: 6.3
I don't have the Delphi.Personality (using C++) ie I can't use the demo projects out of the box. Anyway, the problem is due to the following in TBaseVirtualTree.WMKeyDown; if I remove the else-part it works.
That is, if the user hits VK_BACK to edit a cell it will work sometimes depending where in the tree the cell is located. Anyway close if you like, I can live with the internal patch...

```
VK_BACK:
  if tsIncrementalSearching in FStates then
    DoStateChange([tsIncrementalSearchPending])
  else
    if Assigned(FFocusedNode) and (FFocusedNode.Parent <> FRoot) then
      FocusedNode := FocusedNode.Parent;
```

**Comment by joachimmarder** [comment]
> if I remove the else-part it works.

Removing the else part is not an option, because this is typical treeview behavior, as you can see in Windows Explorer.

>  Anyway close if you like,

OK.
