### ISSUE TITLE
With toCenterScrollIntoView, selection by a user invokes the action too

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [JAM-Software/Virtual-TreeView#700]
With toCenterScrollIntoView option enabled, the item selection launched by a user invokes centering of the item as well. I guess this hardly could be desirable behavior. I suggest only center the focused item if it was focused programmatically (including incremental search).

**Comment by joachimmarder** [comment]
I tend to agree, but need to check this in detail.

**Comment by joachimmarder** [comment]
I looked into this and the behavior you described does not occur in case the flag `toDisableAutoscrollOnFocus` is set. `toCenterScrollIntoView` does not turn on or off auto-scrolling, it just decides if the selected nodes is scrolled into the center of the view, or if the viewport is scrolled only as much as necessary so that the focused node appears on the edge of the control.

Please provide more detailed repro steps based on the `Minimal` sample project if you think something does not work as it should.

**Comment by Fr0sT-Brutal** [comment]
Yes you're right (though a use case when toDisableAutoscrollOnFocus could be turned on seems strange to me). But I cannot imagine why centering could be desired when a node is focused by a user. F.i., a list with items 1-10 in view, 20 items total. User clicks on 9th item. The view scrolls, the focused item jumps up, while the cursor stays on old position - and now it is over 15th item. For me, this behavior really confuses and makes this option useless while it would be pretty fine for incremental search.

**Comment by joachimmarder** [comment]
I agree and would never turn on this option in my applications. But I cannot speak for everyone. For example, issue #692 was discovered due to this option, so somebody must have used it.
Windows Explorer by the way does also not center the found node when using incremental search. I will leave this issue open for a while and see if other comments are made.

**Comment by Fr0sT-Brutal** [comment]
Well, Explorer scrolls the view so that the found node becomes first visible. VTV makes it last visible. Behavior already differs ;). Centering the focused node looks pretty but only for big jumps.

**Comment by joachimmarder** [comment]
Fixed for V6.6 in commit 41eb6c3: If the user clicked a node, we are no longer centering this node if the option toCenterScrollIntoView is set.
