### ISSUE TITLE
Drop support for Windows XP / 2003 in V7

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#707]
This code is no longer actively tested by anyone on Windows XP / 2003. This is why i vote for dropping support for Windows XP/2003 in [V7](https://github.com/Virtual-TreeView/Virtual-TreeView/milestone/10). The V6 branch can be used by those who still need XP compatibility.

**Comment by Fr0sT-Brutal** [comment]
Will this simplify code? If no, why not just mention these OS'es as untested, usable at own risk and 'here be dragons'?

**Comment by joachimmarder** [comment]
> why not just mention these OS'es as untested, usable at own risk 

Well, that's more or less the status quo. But is this really a good state? Wouldn't it be better to have a branch known to be XP compatible?

And what happens if someone reports a problem on XP for the GitHub master? Fix it or leave it be?

**Comment by Fr0sT-Brutal** [comment]
You can just fix a revision (or version) that will be the last to support XP officially and mention it in Readme. Further revisions could be used without any warranties and bug reports.
Regarding separate branch, it depends on whether you plan to accept compatibility fixes to it. If the code will just be sealed, then the branch will be not more than just a tag on a revision.
Anyway you can always add that separate branch if XP compatibility would appear important to somebody.

**Comment by joachimmarder** [comment]
> Regarding separate branch, it depends on whether you plan to accept compatibility fixes to it

Of course I will accept pull requests and patches for that branch, which will not be a pure XP-branch but a V6 branch. I cannot promise how much of my time I will invest in this branch for debugging and fixing, especially when it comes to XP-specific bugs, but the idea of that branch is that this should ideally not happen, because it is derived from a stable and XP-compatible source.

**Comment by Fr0sT-Brutal** [comment]
If I were you, I'd mark last V6 as the last official XP-compatible revision and mention that further revisions may work or may not. And that's all for the beginning. Then, if somebody would send a PR you can decide: whether to apply it to V6 branch or split out a separate branch or merge it to upstream and mark the revision "probably XP compatible".

**Comment by IgitBuh** [comment]
I'd just like to mention that as a software developer I cannot exclude XP users just like that. In my case there are still about 5% XP users. That's still too many to abandon.

**Comment by joachimmarder** [comment]
I don't want force you to exclude XP users, you just have to stick with V6 for some more months if those are important fo you. I am going to tell my XP users with the next major release of my application that they should use the previous version of my application.

**Comment by IgitBuh** [comment]
I understand that I can stick to V6, but I believe we're talking about a couple more years - not months. Although XP is out of its lifecycle for Microsoft, there are still many users in countries with less wealth and also business users in the automated industry (who now pay Microsoft for ongoing XP patches). Both groups are relevant to me, but I cannot maintain two different version branches of my software just because of VTV.
I believe, other developers of software that already exists 10+ years would agree. Just my 2c.

**Comment by joachimmarder** [comment]
> I believe, other developers of software that already exists 10+ years would agree

My software TreeSize exists since 21 years and I disagree. I have a branch with XP compatiblity that will receive only critical bugfixes and no new features (like XP does for 10 years now). My main development branch is no longer XP compatible which simplifies code and testing.

**Comment by IgitBuh** [comment]
I didn't say _all_ developers would agree, but I'm sure that there are a lot who think the same as I do now. It's clear that you see it differently, otherwise you wouldn't have suggested this change in the first place.
I simply wanted to provide a different point of view to this discussion. The result of dropping XP support for V7 would be to leave a lot of developers behind for at least a couple of years.

**Comment by Fr0sT-Brutal** [comment]
Guys, is there really a matter to argue about? Any important functions that appeared only in Vista+? Or maybe obsolete XP functions that make code ugly/long/whatever? OTOH, is there any crucial VTV feature someone urgently lacks in current version?
From my POV, there's no big problem. New API's probably could be used via wrappers. New releases could be marked as "untested for XP, use at your own risk". New fixes and features could be backported to V6 branch just as it is done for XE2. Anyway this is open source and there's much more possibilities to keep support of ancient compilers/OS-es comparing to closed source (like XP itself).

**Comment by joachimmarder** [comment]
> be marked as "untested for XP, use at your own risk". 

I don't think that this uncertain state is really helpful for a developer who requires XP-support. I think it would be better for those to stick with V6.

>  New fixes and features could be backported to V6 branch just as it is done for XE2. 

+1

**Comment by joachimmarder** [comment]
> otherwise you wouldn't have suggested this change in the first place.
> I simply wanted to provide a different point of view to this discussion.

Well, I was hoping for posts that not only tell me "I prefer if you keep XP compatible" but also propose approaches how this could be done in practical, especially regarding testing and fixing on XP. 

For VTV V6 I have a significant user base on XP, but for V7 I won't have a single XP user.

**Comment by Candesco** [comment]
I think if a developer really requires XP support, than he also has good access to XP and can therefor fix the problem himself.
So I'd more or less fix it via pull requests only.

Some time ago you could download a VM from MS to test things on XP, but they took it offline shortly after they dropped public XP support. So I wouldn't know of a good solution to test this, without keeping some XP machine or VM of your own. Though I'd really recommend using the latter, since the former may break at some point and the latter can be transferred and backed up rather easily.

**Comment by joachimmarder** [comment]
> So I wouldn't know of a good solution to test this, without keeping some XP machine or VM of your own.

I am aware that there are solutions, but I don't want to spend my time on them.

> So I'd more or less fix it via pull requests only.

Yep, as long as the code quality is sufficient and the code does not get too fragmented by switches for XP/non-XP. I still thin an XP branch is the best solution, especially because it is unlikely to break that XP support breaks here.

**Comment by joachimmarder** [comment]
The support for Windows XP/2003 has been dropped (issue #707). This means:
- We did not intentionally break XP support.
- We do no longer test on Windows XP/2003
- We may accept pull request for XP support if the code quality is sufficient.
- We recommend to use the V6 branch on Windows XP
