### ISSUE TITLE
Use System.Threading instead of WorkerThread

### ISSUE THREAD

**Issue by pyscripter** [JAM-Software/Virtual-TreeView#786]
On XE7 and higher System.Threading is available.  Would you consider a PR that uses System.Threading instead of WorkerThread unit on XE7 or higher (using conditional compilation)?
There would be a couple of advantages.
-  If an application already uses System.Threading it is more efficient to handle validation through the System.Threading Thread Pool instead of having a separate thread.
-  The Worker thread is created whether it is needed or not. (even when CacheThreshold is not reached).  System.Threading only creates threads when needed.  No tasks -> no threads.

The changes needed are quite minimal.

And a question.   DoValidateCache is executed inside the thread.   DoValidateCache calls UpdateScrollBars if toVariableNodeHeight is set.  Is UpdateScrollbars thread safe?  Shouldn't the call to UpdateScrollbars be queued?

**Comment by joachimmarder** [comment]
I am reluctant to do this. This means `$ifdef`s in the code which is always bad. You cannot be sure that the code compiles in all combinations of `$ifdef`s.

Furthermore this would introduce `System.Threading` just for this small task. We for example use the ThreadPool that used to be part of our ShellBrowser components because `System.Threading` still lacks an easy to use concept for cancellation, e.g. a cancellation token. Others use OmniThreadLibrary. And having two threadpools in an application is quite some overhead.

> The Worker thread is created whether it is needed or not. 

This is something we can work on, but a thread that has no work does not mean a significant overhead.

**Comment by joachimmarder** [comment]
> Shouldn't the call to UpdateScrollbars be queued?

Yes, I think so, because it deals with window handles. I am going to change that.

**Comment by pyscripter** [comment]
Good.  I am convinced.   You can close this issue and open a new one for the UpdateScrollBars bit.

**Comment by joachimmarder** [comment]
The `UpdateScrollbars()` issue is already fixed. I opened #787 to create the `TWorkerThread` only when needed.
