### ISSUE TITLE
Double click does not work because of a hint

### ISSUE THREAD

**Issue by supasoft** [JAM-Software/Virtual-TreeView#814]
HintMode: hmTooltip.
Open the second form with the key when the tooltip is visible.
The second form does not work Double click when the tooltip is visible.

procedure TForm3.FormCreate(Sender: TObject);
begin
  vt.RootNodeCount := 5;
end;

procedure TForm3.vtDblClick(Sender: TObject);
var
  Form: TForm3;
begin
//  Application.CancelHint; // this fixes the error
  Form := TForm3.Create(Self);
  Form.ShowModal;
  Form.Free;
end;

procedure TForm3.vtGetText(Sender: TBaseVirtualTree; Node: PVirtualNode; Column: TColumnIndex; TextType: TVSTTextType;
  var CellText: string);
begin
  CellText := '1111111111111111111111111111111111111111';
end;

procedure TForm3.vtKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState);
begin
  if Key = VK_F2 then
    vtDblClick(nil);
end;

**Comment by joachimmarder** [comment]
Can you please attach a sample as ZIP-file that compiles?

**Comment by supasoft** [comment]
Yes.
![2018-07-09_11-34-35](https://user-images.githubusercontent.com/40602544/42495145-ed8d311a-842a-11e8-984a-26892a223e3f.png)
[VirtualTreeView Hint.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2179244/VirtualTreeView.Hint.zip)

**Comment by sanjayssk** [comment]
I'm not able to reproduce this most of the time. It happens for me only some times, that too when I'm several levels down with many dialogs. Trying to get a consistent method to reproduce the problem.

**Comment by sanjayssk** [comment]
Found the condition. If F2 is pressed while the hint is ON to create new dialog, only then the new dialog stops responding. In all other cases, it continues to work.

**Comment by sanjayssk** [comment]
Joachim,

The solution of this problem is to eliminate override of IsHintMsg in the derived TVirtualTreeHintWindow class. The purpose of IsHintWindow is to determine if the hint window can be canceled and there is already a default behavior in VCL which may be good enough after all these years of VCL evolution.

The code in the overide is unnecessarily complex and tries to be too clever to override the default VCL behavior.  Unless, of course, someone says this overriding code is needed and can give some testcases to prove that it is needed.

I suggest that we comment the code and put the following instead so that the code remains in case some issue is seen in future that requires it.

  `Result := inherited IsHintMsg(Msg);`

Please confirm.

Regards,
Sanjay

**Comment by sanjayssk** [comment]
I'm in doubt about the last Else part. May be that is still needed to be called unconditionally. But I don't have a testcase to show that it is needed. Please advise.

    // Work around problems with keypresses while doing hint animation.
    if HandleAllocated and IsWindowVisible(Handle) and (Msg.Message >= WM_KEYFIRST) and 
           (Msg.Message <= WM_KEYLAST) and
           (tsInAnimation in FHintData.Tree.FStates) and TranslateMessage(Msg) then
      DispatchMessage(Msg);

**Comment by joachimmarder** [comment]
Hi Sanjay.

It's difficuklt for me to give an advice here. I never touched or
investigated the code of the TVirtualTreeHintWindow after I took overt VTV
because it looked so horrible. I was hoping that we maybe could eliminate
it or make it optional, becuase the VCL THintWindow should be good eneough
meanwhile. See also
https://github.com/Virtual-TreeView/Virtual-TreeView/issues/770

So maybe we should make this issue dependent on #770?

Best regards,

Joachim



2018-08-07 9:24 GMT+02:00 Sanjay Kanade <notifications@github.com>:

**Comment by sanjayssk** [comment]
Good idea. You removed HintAnimation anyway and the code is related to that.

**Comment by sanjayssk** [comment]
Joachim,

Do you think tsInAnimation state is only related to Hint Animation and will now never occur as HintAnimation property is removed? If so, I can do away with Else part and solve this issue.

Thanks,
Sanjay

**Comment by joachimmarder** [comment]
The `HintAnimation` property has been removed, but the member is still there and has its default value assigned. I wanted to remove the member in a second step.

**Comment by joachimmarder** [comment]
@sanjayssk : Most of #770 has been done, so you can try removing the else part.

**Comment by joachimmarder** [comment]
The problem is solved if I remove the condition `or ((Msg.Message >= WM_KEYFIRST) and (Msg.Message <= WM_KEYLAST))` from the if-statement in `IsHintMsg()`. This code was added by the original developers so that tooltip windows stay visible during keyboard navigation. Not sure if this is essential, it seems to be a non-standard behavior for Windows controls.

Only cursor keys will now prevent the hint window from disappearing.
