### ISSUE TITLE
AddToSelection not always called when dragging the mouse

### ISSUE THREAD

**Issue by ThomasHThomasH** [JAM-Software/Virtual-TreeView#875]
I have set up the virtual treeview with the following options: 

`Header.options := [hoColumnResize, hoDrag, hoVisible, hoDblClickResize];`
`TreeOptions.MiscOptions := [toGridExtensions, toEditable];`
 `TreeOptions.SelectionOptions := [toExtendedFocus, toSimpleDrawSelection, toMultiSelect, toDisableDrawSelection];`
`TreeOptions.paintOptions := [toShowTreeLines, toShowHorzGridLines, toShowVertGridLines];`

When I try to select multiple nodes by dragging the mouse, occasionaly a node doesn't get selected. The AddToSelection method is not called. This only happens to me when dragging from top to bottom, not when I drag from the bottom to the top. 

When I remove the options 'toGridExtensions', this problem is solved.

Version: 6.7.0
`

**Comment by joachimmarder** [comment]
Please respect our guidelines for reporting bugs as written on project homepage: First make sure to use the [latest version](https://github.com/Virtual-TreeView/Virtual-TreeView/archive/master.zip) of Virtual TreeView. And please provide a [sample project](https://github.com/Virtual-TreeView/Virtual-TreeView/tree/master/Demos) that allows us to replicate the bug, or provide in detail how one needs to modify one of the included sample projects so that the bug occurs.

**Comment by joachimmarder** [comment]
No reply from reporter => close
