### ISSUE TITLE
Horizontal scroll bar changes size unneccessarily

### ISSUE THREAD

**Issue by jam-kiefer** [JAM-Software/Virtual-TreeView#883]
See the attached sample.

Repro:
 * scroll down
Actual behavior: the horizontal scroll bar handle becomes shorter when longer node titles come into view. This is just the expected behavior because node widths are not yet initialized for nodes out-of-view.
 * scroll up
Actual behavior: the horizontal scroll bar handle becomes longer again.
Expected: the handle length stays as it is, because the VTV should keep the state of how wide the longest node title is (of those yet initialized).

[GlitchyHorizontalScrollbar.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/2956102/GlitchyHorizontalScrollbar.zip)

**Comment by joachimmarder** [comment]
[Issue883.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/3015253/Issue883.zip)
Improved Sample project

**Comment by joachimmarder** [comment]
Difficult to solve. It seems that it was an intentional decision to take only the visible nodes into account. Taking all nodes into account could lead to performance problems.
We could cache the maximum seen width in `TBaseVirtualTree.GetMaxRightExtend()`, but we would need to invalidate this cache once the node that has the maximum width is removed.

**Comment by joachimmarder** [comment]
No further contributions to the discussion, so closing this issue and the behavior remains is it was the past years.
