### ISSUE TITLE
Black background in Icons for vsDisabled nodes - BUG?

### ISSUE THREAD

**Issue by Johnyy45** [JAM-Software/Virtual-TreeView#924]
Hello. I am using Delphi XE10.3 and VST V7.2.1: (07 Mar 2019).

I added some nodes, and perform for this nodes:
include(pNode^.States,  vsDisabled);

Nodes become disabled:
![quest](https://user-images.githubusercontent.com/44755939/65429130-180f5d00-de2f-11e9-9f27-727e1d8412ff.png)

Text color is gray, but icons have black background!

OnGetImageIndex like this:

```
if ( Kind in [ikNormal, ikSelected   ]) then begin
 case Column of
...
```

How can I remove the black background?

**Comment by joachimmarder** [comment]
Please respect our guidelines for reporting bugs as written on project homepage and provide a sample project that allows us to replicate the bug, or provide in detail how one needs to modify one of the [included sample project](https://github.com/Virtual-TreeView/Virtual-TreeView/tree/master/Demos) so that the bug occurs.

Images in General Abilities demo don't have a black border if I disable all nodes:
![grafik](https://user-images.githubusercontent.com/10615289/65465692-38eea700-de5d-11e9-8daa-2f1b00b7f068.png)

**Comment by Johnyy45** [comment]
I found a problem. It is Project Options - Application - Manifest (it was selected None).
I selected Auto Generate and problem was solved.

Screenshot and test project in attachment
![4](https://user-images.githubusercontent.com/44755939/65512322-6a658200-def2-11e9-891b-0ff460ef406d.png)

[S1.zip](https://github.com/Virtual-TreeView/Virtual-TreeView/files/3647184/S1.zip)

**Comment by Johnyy45** [comment]
But problem is actual, because project must be compiled without manifest

**Comment by joachimmarder** [comment]
Without a manifest Windows starts an application in a kind of Windows 2000 compatibility mode, but Virtual TreeView V7 no longer supports Windows 2000. So this is a not supported scenario.
