### ISSUE TITLE
auto invalidate when each form opened

### ISSUE THREAD

**Issue by DRAMA22** [JAM-Software/Virtual-TreeView#934]
i am using tvirtualstringtree with some animated gifs 

i got a problem when i open a new form or move the window the tvirtualstringtree keeps invalidate 

any idea why that happened and how to fix it ?

**Comment by DRAMA22** [comment]
also if i use StretchDraw any where in my code the virtuailstringtree get invalidated automatically

**Comment by joachimmarder** [comment]
> i am using tvirtualstringtree with some animated gifs

As far as I know Virtual TreeView does not support animated GIFs.

Please respect our guidelines for reporting bugs as written on project homepage and provide a sample project that allows us to replicate the bug, or provide in detail how one needs to modify one of the [included sample project](https://github.com/Virtual-TreeView/Virtual-TreeView/tree/master/Demos) so that the bug occurs.

**Comment by DRAMA22** [comment]
after debugging that was an Timage invalidation it not related to VST which cause the entire form and controls to be invalidated any way that wasn't VST ISSUE thanks
