### ISSUE TITLE
I have double image in tree

### ISSUE THREAD

**Issue by Sam130687** [JAM-Software/Virtual-TreeView#937]
I have some mistake in component. We have: windows 10*64, Delphi RIO and this:
![image](https://user-images.githubusercontent.com/58412574/69932207-3c488380-14db-11ea-844b-ec8575b2f9ad.png)
What i do bad?

**Comment by joachimmarder** [comment]
Please do not use issues for getting support. Try to get support from the community e.g. at [Stack Overflow](http://stackoverflow.com/search?q=%22virtual+treeview%22) or [Delphi Pages](http://www.delphipages.com/).

When reporting a bug, please respect our guidelines for reporting bugs as written on project homepage: First make sure to use the [latest version](https://github.com/Virtual-TreeView/Virtual-TreeView/archive/master.zip) of Virtual TreeView. 
And please provide a sample project that allows us to replicate the bug, or provide in detail how one needs to modify one of the [included sample project](https://github.com/Virtual-TreeView/Virtual-TreeView/tree/master/Demos) so that the bug occurs.

Most likely you did not respect the `TImageKind` parameter.
