### ISSUE TITLE
Getimageindex doesnt draw images to VST

### ISSUE THREAD

**Issue by DRAMA22** [JAM-Software/Virtual-TreeView#938]
i have this code 

`procedure TFORM1.VSTGetImageIndex(Sender: TBaseVirtualTree;
  Node: PVirtualNode; Kind: TVTImageKind; Column: TColumnIndex;
  var Ghosted: Boolean; var ImageIndex: TImageIndex);
begin
if not Assigned(Node) then
begin
exit;
end;

if Kind in [ikNormal , ikSelected] then // Either Selected or not
begin
if Column = 0 then
begin
ImageIndex := 0;
end;

end;

end;`

and i have assigned an imagelist to VST Property 

after inserting nodes the imageindex doesnt show the icons in imagelist any idea why ?

**Comment by joachimmarder** [comment]
And `ikOverlay`?

**Comment by DRAMA22** [comment]
even i tried 

`if Kind in [ikNormal , ikSelected, ikoverlay] then
begin
case Column of
0: ImageIndex := 0;
end;
`

it doesnt show the image index

**Comment by joachimmarder** [comment]
> after inserting nodes the imageindex doesnt show the icons in imagelist any idea why ?

No.

When reporting a bug, please respect our guidelines for reporting bugs as written on project homepage: First make sure to use the [latest version](https://github.com/Virtual-TreeView/Virtual-TreeView/archive/master.zip) of Virtual TreeView. 
And please provide a sample project that allows us to replicate the bug, or provide in detail how one needs to modify one of the [included sample project](https://github.com/Virtual-TreeView/Virtual-TreeView/tree/master/Demos) so that the bug occurs.
