### ISSUE TITLE
Draw hint option doesn't work

### ISSUE THREAD

**Issue by albertofll** [JAM-Software/Virtual-TreeView#952]
An old code in a program that implemented drawing the hint in TVirtualDrawTree does not work, I can not specify from what moment it stopped doing so , my tests are with:

- Windows 10.
- Delphi 10.3.3
- I've checked the demo that comes with the components (Advanced demo -> DrawTreeDemo) and it doesn't work either.
- ShowHint: = true.
- HintMode: = hmHint;
- Implemented OnGetHintSize and OnDrawHint event.

**Comment by joachimmarder** [comment]
I never used `TVirtualDrawTree` myself. The reason for the missing hint seems to be that `TVirtualDrawTree` overrides `GetDefaultHintKind()` and returns `vhkOwnerDraw`.  One possible fix would be to use the `OnGetHintKind` event in your project in order to return `vhkText`. Another option would be to use the `OnDrawHint` in order to draw the owner drawn hint.

But I think it would make more sens to not override `TVirtualDrawTree.GetDefaultHintKind()`, which I propose as solution.

**Comment by albertofll** [comment]
Hello, the hint I try to show is `ownerdraw`, not just text, so I draw on the canvas in the `OnDrawHint ` event. As I said the same code worked in an earlier version of TVirtualDrawTree, the same Advanced example (DrawTreeDemo) that comes as a sample has a code that uses it.

**Comment by joachimmarder** [comment]
> I've checked the demo that comes with the components (Advanced demo -> DrawTreeDemo) and it doesn't work either.

It is working for me. Please keep in mind that the hint works only for images and only in the second column (column index 1).

**Comment by joachimmarder** [comment]
No further comments from reporter => Close
