### ISSUE TITLE
Access Violation when trying to edit a node in a collapsed node via Shortcut

### ISSUE THREAD

**Issue by delphi-sucks** [JAM-Software/Virtual-TreeView#977]
### Description
If you try to edit a Node with the Shortcut F2 which is hidden, but still focused, inside a collapsed parent node, you crash with an Access Violation.

```delphi
procedure TBaseVirtualTree.DoEdit;

begin
  Application.CancelHint;
  StopTimer(ScrollTimer);
  StopTimer(EditTimer);
  DoStateChange([], [tsEditPending]);
  if Assigned(FFocusedNode) and not (vsDisabled in FFocusedNode.States) and
    not (toReadOnly in FOptions.FMiscOptions) and (FEditLink = nil) then
  begin
    FEditLink := DoCreateEditor(FFocusedNode, FEditColumn);
    if Assigned(FEditLink) then
    begin
      DoStateChange([tsEditing], [tsDrawSelecting, tsDrawSelPending, tsToggleFocusedSelection, tsOLEDragPending,
        tsOLEDragging, tsClearPending, tsDrawSelPending, tsScrollPending, tsScrolling]);
      ScrollIntoView(FFocusedNode, toCenterScrollIntoView in FOptions.SelectionOptions,
        not (toDisableAutoscrollOnEdit in FOptions.AutoOptions));
      if FEditLink.PrepareEdit(Self, FFocusedNode, FEditColumn) then // <=== HERE, FEditLink = nil
      begin
```

### Steps to Reproduce
1. Open the project Minimal from the Demos-Folder
2. Compile & Run
3. Select a node
4. "Add node(s) as children"
5. Select a child node
6. Collapse parent node without changing the focus by clicking on the [-]
7. Press F2
=> Node expands and crashes with an Access Violation

### Additional Information
Reproduced in 7.4 and latest master-Branch

**Comment by joachimmarder** [comment]
I see 3 options for handling this situation:
1. If the focused node gets invisible because of a collapse, select a parent node that is visible.
2. Before entering the edit state, expand all parent nodes of the focused node so that it gets visible.
3. Do nothing if the user tries to edit a node and no node is selected or the focused node is not visible because it is collapsed.

I vote for option 2, as it can be implemented with a minimum impact.
