### ISSUE TITLE
toRestoreSelection works unexpected in case multiple items have the same name

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#981]
Currently the code behind the `toRestoreSelection` uses the text of column 0 to restore the selection after a refill of the control.

In case multiple items with the same text exists, this produces unexpected results, e.g. more nodes are selected than it was orignally the case.

**Comment by joachimmarder** [comment]
Proposed change: Introduce new public property RestoreSelectionUniqueColumn. The getter will return MainColumn unless the developer assigned another value.

**Comment by luebbe** [comment]
Haven't looked at the code, but it sounds like the selected strings are stored for comparison. I guess you can never make sure that the values in a column are unique.
Would it make sense to have unique ids in the node instead?

**Comment by joachimmarder** [comment]
> Would it make sense to have unique ids in the node instead?

That would solve the issue comprehensively, but due to virtual nature of the control, this UID needs to be provided by the application, so that it stays the same after a refill of the control. And the ID needs to be stored with every node and consumes memory, but would be useful only in corner cases.

Therefore, the idea to use already existing information and allow the developer to mark one column as the one with unique information, instead of using a fix column index 0.

**Comment by Ajoschi** [comment]
@joachimmarder : 2 Lines of code in VirtualTrees.pas need to be adjusted in order to make this work as expected:
1. TCustomVirtualStringTree.AddToSelection: Relative line 13 -> Pass "Header.RestoreSelectionColumnIndex" instead of 0 as 3rd Parameter to call Self.OnGetText()
2. TCustomVirtualStringTree.RemoveFromSelection: Relative line 8-> Pass "Header.RestoreSelectionColumnIndex" instead of 0 as 3rd Parameter to call Self.OnGetText()
