### ISSUE TITLE
Fixed column wider than ClientWidth of the control cannot be resized any more

### ISSUE THREAD

**Issue by joachimmarder** [JAM-Software/Virtual-TreeView#998]
Make a column fixed using the coFixed flag and make it larger than the ClientWidth of the control. Neither scrolling nor resizing the column works any more.

**Comment by joachimmarder** [comment]
By setting TVTHeader.FixedAreaConstraints.maxWidthPercent to 95 this problem can be fixed.

Would it make sense to use a default value of 95 for this property, instead of not limiting it?

**Comment by obones** [comment]
Hello,

I'm having an issue with the change to the `if` statement done in the associated commit.
Right below it, it makes this code: 

            if (FMinWidthPercent > 0) and (FixedWidth < MinFixedWidth) then
              ResizeColumns(MinFixedWidth - FixedWidth, 0, Count - 1, [coVisible, coFixed]);

being called with the first argument set at `42`
This means that inside `ResizeColumns` we have `BonusPixel` set to `True` which means that the local `ReduceConstraints` method will always return `True`

My issue comes from the fact that `ReduceConstraints` is used as a stop condition for the smaller `repeat..until` loop if `MaxDelta` is lower than `Abs(ChangeBy)`
In my case, the test right above that decides to call `IncDelta` is always `False` because `(Options * FColumns[I].Options = Options)` is `False` for all columns.
This means that `MaxDelta` keeps its default value of `0` and there is no way to escape the `repeat..until` loop resulting in an unresponsive application eating up one CPU core.

I have reverted the change to the `if` condition locally, but I'm not sure that this is an appropriate course of action

**Comment by joachimmarder** [comment]
> I have reverted the change to the if condition locally, but I'm not sure that this is an appropriate course of action

Reverting the change to the `if` statement brings back the problem that the `MaxWidthPercent` property is not taken into account. I guess that just covered the problem you encountered here, and the change is the trigger but not the root cause. But I have to admit that I never looked into this code so far. Reading your bug report above may explain why....

**Comment by obones** [comment]
Yes, you are right, the erroneous `if` statement is most likely hiding a deeper issue. But between breaking a property that I do not use and having an infinite loop that blocks my application, I took the shortest route for my own use case.

Obviously, it would be much nicer to have both the `if` statement and the `MaxDelta` loop function properly.

**Comment by joachimmarder** [comment]
Can you provide a sample project or the relevant property settings that allow me to reproduce the infinite loop? Even better would be a unit test.

**Comment by obones** [comment]
Here you are: [VTVHeaderMinWidthPercent.zip](https://github.com/JAM-Software/Virtual-TreeView/files/6425829/VTVHeaderMinWidthPercent.zip)

The only thing that was done here is to set `Header.FixedAreaConstraints.MinWidthPercent` to 5

**Comment by joachimmarder** [comment]
Sorry for the late response @obones. It seems that the form file "MainForm" is missing in the ZIP archive.

**Comment by obones** [comment]
Woah, sorry about that, here is a valid zip:

[VTVHeaderMinWidthPercent.zip](https://github.com/JAM-Software/Virtual-TreeView/files/6675396/VTVHeaderMinWidthPercent.zip)

**Comment by joachimmarder** [comment]
@obones, thanks for the complete sample. The Virtual TreeView control in the sample has no columns defined, and so `TVTHeader.ResizeColumns()` is called with the parameter `RangeEndCol` having a value of -1 (`Column.Count - 1`). This causes the for-loops to not loop and so do nothing. 

It seems valid to me to do nothing in `ResizeColumns()` of no columns are defined, and I changed the code accordingly.
